version: '3.7'

services:
  postgres:
    image: postgres:14-alpine
    container_name: dbpostgres
    ports:
      - 5432:5432
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - planograma-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: back-planograma
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@dbpostgres:5432/${POSTGRES_DB}"
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    networks:
      - planograma-network

volumes:
  pgdata:
    driver: bridge    

networks:
  planograma-network:
    driver: bridge
