version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: db-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}  
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}  
      POSTGRES_DB: ${POSTGRES_DB} 
    volumes:
      - pgdata:/var/lib/postgresql/data 
    networks:
      - planograma-network

volumes:
  pgdata:
    driver: local    

networks:
  planograma-network:
    external: true
    
