name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Install dependencies
        run: npm install
        
      - name: Run lint
        run: npm run lint
        
  # test:
  #   needs: lint
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2
        
  #     - name: Install dependencies
  #       run: npm install
        
  #     - name: Run tests
  #       run: npm run test

  build-and-deploy:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and tag Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/back-planograma:latest .
          docker tag ${{ secrets.DOCKER_USERNAME }}/back-planograma:latest ${{ secrets.DOCKER_USERNAME }}/back-planograma:latest

      - name: Install Docker Scout
        run: |
          curl -fsSL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh | sh
          export PATH=$HOME/.docker/cli-plugins:$PATH
          docker scout version

      - name: Scan image with Docker Scout
        run: |
          docker scout quickview ${{ secrets.DOCKER_USERNAME }}/back-planograma:latest
          docker scout cves ${{ secrets.DOCKER_USERNAME }}/back-planograma:latest
          
      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/back-planograma:latest

      - name: Trigger Portainer Webhook
        run: curl -X POST "${{ secrets.PORTAINER_WEBHOOK }}"
